#     _____ _            ___  _ _
#    |  __ (_)          / _ \| | |
#    | |  \/___   _____/ /_\ \ | |   Made by:
#    | | __| \ \ / / _ \  _  | | |   BlitzGamer_88
#    | |_\ \ |\ V /  __/ | | | | |
#     \____/_| \_/ \___\_| |_/_|_|

# If you enable this, items will be given to the player that uses /giveall as well.
giveItemsToSender: false
# If you enable this, only players with the permission 'giveAllReceivePermission' will receive the items/money.
requirePermissionToGetItems: false


# Customize the messages that are sent by the plugin:
itemCannotBeAir: '&cYou can''t send air.'
onlyPlayersCanUseRadius: '&cOnly players can use the radius functionality.'
amountCannotBeZero: '&cYou can''t send $0.'
wrongWorldName: '&cCould not find the world you specified.'
fullInventory: '&cYour inventory is full!!'

# Only messages where you can use the custom placeholders: %amount%, %material%, %radius% and %world%
itemsReceived: '&3You have received &a%amount% %material%&3.'
itemsSent: '&aYou have given everyone: &3%amount% %material%&a.'
itemsSentWorld: '&aYou have given everyone in &3%world%&a: &3%amount% %material%&a.'
itemsSentRadius: '&aYou have given everyone in a %radius% blocks radius: %amount% %material%'
moneyReceived: '&3You have received &a$%amount%&3.'
moneySent: '&aYou have given everyone &3$%amount%&a.'
moneySentWorld: '&aYou have given everyone in &3%world%&a: &3$%amount%&a.'
moneySentRadius: '&aYou have given everyone in a &3%radius% blocks&a radius: &3$%amount%&a.'

wrongUsage: '&cWrong usage!'
noOneOnline: '&7No player has been found so no items have been sent.'
noOneOnlineMoney: '&7No player has been found so no money has been sent.'
noPermission: '&cError: &7You don''t have permission to do that!'
configReloaded: '&7Config reloaded.'

# This message is sent only if 'giveItemsToSender' is disabled
onlyYouOnline: '&7You are the only one online.'
